apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    {{- include "k6-quick-start-test.labels" . | nindent 4 }}
spec:
  volumes:
    - name: "{{ .Chart.Name }}-reports"
      emptyDir: {}
    - name: "{{ .Chart.Name }}-logs"
      emptyDir: {}
  containers:
    - name: "{{ $.Chart.Name }}"
      image: {{ $.Values.images.testwareImage | quote }}
      env:
        - name: "APP_VERSION"
          value: "{{ include "get-application-version" $ | trim | default "undefined" }}"
        - name: "BUILD_URL"
          value: {{ $.Values.env.BUILD_URL }}
        - name: "STAGING_TYPE"
          value: {{ $.Values.env.STAGING_TYPE }}
        - name: "PRODUCT"
          value: {{ $.Values.env.PRODUCT }}
        - name: "PRODUCT_VERSION"
          value: "{{ include "get-product-version" $ | trim | default "undefined" }}"
        - name: "ENVIRONMENT"
          value: {{ $.Values.env.ENVIRONMENT }}
        - name: "hostname_url_v"
          value: {{ $.Values.env.hostname_url }}
        - name: "hostname_url_cm"
          valueFrom:
            configMapKeyRef:
              name: testware-hostnames
              key: "th"
              optional: true
        - name: "IAM_HOST_V"
          value: {{ $.Values.env.IAM_HOST }}
        - name: "IAM_HOST_CM"
          valueFrom:
            configMapKeyRef:
              name: testware-hostnames
              key: "iam"
              optional: true
        - name: "EIC_HOST_V"
          value: {{ $.Values.env.EIC_HOST }}
        - name: "EIC_HOST_CM"
          valueFrom:
            configMapKeyRef:
              name: testware-hostnames
              key: "iam"
              optional: true
        - name: "GAS_HOST_V"
          value: {{ $.Values.env.GAS_HOST }}
        - name: "GAS_HOST_CM"
          valueFrom:
            configMapKeyRef:
              name: testware-hostnames
              key: "gas"
              optional: true
        - name: "SEF_STATUS_V"
          value: {{ $.Values.env.SEF_STATUS }}
        - name: "SEF_STATUS_CM"
          valueFrom:
            configMapKeyRef:
              name: testware-global-config
              key: "sef-enabled"
              optional: true
        - name: "SEF_ENABLED_TESTS"
          value: "{{ $.Values.env.SEF_ENABLED_TESTS }}"
        - name: OPTIONS_FILE
          value: "/resources/config/{{ $.Values.env.OPTIONS_FILE }}"
        - name: ADDITIONAL_ARGS
          value: {{ $.Values.env.ADDITIONAL_ARGS }}
        - name: TESTWARE_NAME
          value: {{ $.Values.env.TESTWARE_NAME }}
        - name: TEST_VERSION
          value: {{ $.Values.env.TEST_VERSION }}
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: testware-resources-secret
              key: database_url
        - name: K6_TOOL_GUI_URL
          valueFrom:
            secretKeyRef:
              name: testware-resources-secret
              key: gui_url
        - name: API_URL
          valueFrom:
            secretKeyRef:
              name: testware-resources-secret
              key: api_url
        - name: TARGET_CLUSTER
          value: "{{ $.Values.env.TARGET_CLUSTER }}"
        - name: TARGET_NAMESPACE
          value: "{{ $.Values.env.TARGET_NAMESPACE }}"
      volumeMounts:
        - name: "{{ $.Chart.Name }}-reports"
          mountPath: "/reports"
        - name: "{{ .Chart.Name }}-logs"
          mountPath: "/var/log"
      imagePullPolicy: Always
      resources: {}
      securityContext:
        allowPrivilegeEscalation: true
        runAsNonRoot: false
        runAsUser: 0
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
  dnsPolicy: ClusterFirst
  imagePullSecrets:
    - name: k8s-registry-secret
  schedulerName: default-scheduler
  restartPolicy: Never
  securityContext: {}
  terminationGracePeriodSeconds: 5